### ISSUE TITLE
magisk and hook use question

### ISSUE THREAD

**Issue by SkywardSky** [trustdecision/trustdevice-android#18]
magisk error detect，phone not has magisk，but detected install magisk。environment：
phone：vivo U1
model：V1818A
android：8.1.0
vivo room：Funtouch OS_9
software version：PD1818G_A_5.10.32
kernel version：4.9.82-perf+
trustddevice-android branch is master，commit sha : 1cb8f52d1258cec0819310b5789f5dfe013a6c07

use 360 apk reinforcement ，jni hook and debug detect call fail，throw error UnsatisfiedLinkError。environment：
phone：vivo U1
model：V1818A
android：8.1.0
vivo room：Funtouch OS_9
software version：PD1818G_A_5.10.32
kernel version：4.9.82-perf+
trustddevice-android branch is master，commit sha : 1cb8f52d1258cec0819310b5789f5dfe013a6c07

**Comment by SkywardSky** [comment]
trustdevice module abiFilters has

`externalNativeBuild{
            cmake {
                abiFilters 'arm64-v8a','armeabi-v7a','x86'
            }
        }
`

Does not support X86_64 ？

**Comment by wuzuchang** [comment]
> trustdevice module abiFilters has
> 
> `externalNativeBuild{ cmake { abiFilters 'arm64-v8a','armeabi-v7a','x86' } } `
> 
> Does not support X86_64 ？

TrustDevice Pro does not support x86_64, it will not be added here for consistency

**Comment by wuzuchang** [comment]
> 

1. There are currently problems with magisk detection, and we will optimize the detection logic in the future.
2. We need to test and verify the 360 ​​apk reinforcement.

**Comment by wuzuchang** [comment]
> magisk error detect，phone not has magisk，but detected install magisk。environment： phone：vivo U1 model：V1818A android：8.1.0 vivo room：Funtouch OS_9 software version：PD1818G_A_5.10.32 kernel version：4.9.82-perf+ trustddevice-android branch is master，commit sha : [1cb8f52](https://github.com/trustdecision/trustdevice-android/commit/1cb8f52d1258cec0819310b5789f5dfe013a6c07)
> 
> use 360 apk reinforcement ，jni hook and debug detect call fail，throw error UnsatisfiedLinkError。environment： phone：vivo U1 model：V1818A android：8.1.0 vivo room：Funtouch OS_9 software version：PD1818G_A_5.10.32 kernel version：4.9.82-perf+ trustddevice-android branch is master，commit sha : [1cb8f52](https://github.com/trustdecision/trustdevice-android/commit/1cb8f52d1258cec0819310b5789f5dfe013a6c07)

1. There are currently problems with magisk detection, and we will optimize the detection logic in the future.
2. We need to test and verify the 360 ​​apk reinforcement.

**Comment by wuzuchang** [comment]
Test 360 reinforcement did not encounter UnsatisfiedLinkError, check whether trustdevice.so still exists in the apk after reinforcement.

**Comment by SkywardSky** [comment]
thanks
