### ISSUE TITLE
Possible mitigations

### ISSUE THREAD

**Issue by yephny** [trustdecision/trustdevice-android#2]
This is a ltitle unrelated, but I still wanted to ask you if you know of any ways to mask the info picked up by the app? There are several IDs and sensors that can be used along with the list of apps installed to fingerprint the device. I'm wondering whether there's a safe way to spoof this data without breaking any apps.

**Comment by wuzuchang** [comment]
Sorry, your question is really unanswerable. TrustDevice is committed to providing global developers, entrepreneurs and users with compliant, secure and intelligent terminal solutions as well as unique and durable digital device IDs. Besides the GitHub open source version, more information about the professional version can be found on the official website. I hope it helps you.
