### ISSUE TITLE
versionCode not incremented?

### ISSUE THREAD

**Issue by IzzySoft** [trustdecision/trustdevice-android#32]
Looks like with the last release, the `versionCode` was not incremented:

```
Binary files /web/ftp/repo/fdroid/repo/com.trustdevice.android_7.apk and /web/ftp/repo/fdroid/repo/com.trustdevice.android_1.0.7.apk differ
! repo/com.trustdevice.android_7.apk declares sensitive permission(s): android.permission.QUERY_ALL_PACKAGES
! repo/com.trustdevice.android_7.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Looking at the screenshots, I was able to deduce `QUERY_ALL_PACKAGES` (for the list of installed apps), so that warning can already be ignored. As for `DEPENDENCY_INFO_BLOCK`, this can easily be avoided with a small modification to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by lurenman** [comment]
Thank you.  bug has been fixed.

**Comment by IzzySoft** [comment]
Thank you for fixing! :smiley:
