### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [trustdecision/trustdevice-android#6]
Please take care to adjust `versionName` and increase `versionCode` when preparing releases: the APK at the latest release (1.0.1) still identifies as `1.0.0+1` (as [`build.gradle`](https://github.com/trustdecision/trustdevice-android/blob/main/app/build.gradle#L13) tells it). The former is for the "human eye", the latter is used by Android internal to tell versions apart and notify about updates when a higher number was seen. Thanks!

**Comment by collam** [comment]
Thanks for the reminder, we have revised it and we will pay attention to it next time.
